version: '3'
services:
  mall4j-admin:
    restart: always
    container_name: mall4j-admin
    environment:
      - MYSQL_HOST=host.docker.internal
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6379
      - REDIS_DATABASE=0
    image: mall4j-admin:latest
    volumes:
      - /logs/admin:/logs/admin
    ports:
      - 8085:8085
    extra_hosts:
      - host.docker.internal:host-gateway

  mall4j-api:
    restart: always
    container_name: mall4j-api:latest
    environment:
      - MYSQL_HOST=host.docker.internal
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6379
      - REDIS_DATABASE=0
    image: mall4j-api
    volumes:
      - /logs/web:/logs/web
    ports:
      - 8086:8086
    extra_hosts:
      - host.docker.internal:host-gateway

  web:
    image: wineweb:1.0
    container_name: mall4j-web
    ports:
      - 80:80
      - 5880:5880
#    depends_on:
#      - mall4j-admin
#    links:
#      - "mall4j-admin"